apiVersion: v1
kind: ReplicationController
metadata:
  # Change the name
  name: deis-example-rc
  labels:
    heritage: deis
spec:
  replicas: 1

  # Change the selector name
  selector:
    app: deis-example
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        app: deis-example
    spec:
      containers:
        - name: deis-example
        image: deis/example:1.2.3
          ports:
            - containerPort: 80
